feat: custom distbox'es

diff --git a/distbox b/distbox
--- a/distbox
+++ b/distbox
@@ -7,6 +7,17 @@ fi
 
 DISTBOX_IMAGE=registry.fedoraproject.org/fedora-toolbox:latest
 DISTBOX_HOME=$HOME/distbox-home
+DISTBOX_CONTAINER_ID=my-distbox
+
+if [ "$DISTBOX_CUSTOM" != "" ]; then
+    if grep '^[-_0-9a-zA-Z]*$' <<< $DISTBOX_CUSTOM 1> /dev/null; then
+        DISTBOX_HOME=$HOME/distbox-custom/$DISTBOX_CUSTOM
+        DISTBOX_CONTAINER_ID=$DISTBOX_CUSTOM
+    else
+        echo "DISTBOX_CUSTOM is invalid"
+        exit 1
+    fi
+fi
 
 uninstall_distbox() {
     echo y | distbox stop 1> /dev/null 2> /dev/null
@@ -60,7 +71,7 @@ runroot = "$HOME/.config/containers/storage"' > $DISTBOX_HOME/.config/containers
         --env HOME=/home/$USER \
         --env container=podman \
         --env TERMINFO_DIRS=/usr/share/terminfo \
-        --env CONTAINER_ID=my-distbox \
+        --env CONTAINER_ID=$DISTBOX_CONTAINER_ID \
         --volume $DISTBOX_HOME/.local/bin/distrobox-init:/usr/bin/entrypoint:ro \
         --volume $DISTBOX_HOME:/home/$USER \
         --volume /dev:/dev:ro \
